#!/bin/bash

#
# usage ./parallel-ssh
#

# List of servers (you can use IPs or hostnames)
servers=(
  server1.example.com
  server2.example.com
  server3.example.com
)

# The SSH command you want to run
ssh_command="uptime"  # Replace with your command


while getopts u: flag
do
    case "${flag}" in
        # SSH username
        u) username=${OPTARG};;
    esac
done


# Loop through each server and run the command
for server in "${servers[@]}"; do
  echo "Running command on $server with $username..."
  ssh "$username@$server" "$ssh_command"
  echo "-----"
done
